### ISSUE TITLE
Question: How to use glam types (or another lib) directly?

### ISSUE THREAD

**Issue by Nazariglez** [rustgd/glsl-layout#13]
Hey hi, I would like to use glsl-layout to expose the Uniform macro from [notan](https://github.com/Nazariglez/notan) and I was thinking that because notan uses glam, to do that I need to convert with a macro from a struct with glam types, to a struct with glsl-layout types that is at the same converted to internal glsl-types to do the bytes conversion. 

I would like to avoid this triple conversion and just do something like struct with glam types -> struct with inner glsl-layout types, do you have some hint to do that? 

I am thinking of re-export the Uniform trait from notan without requiring the user to install directly glsl-layout, though I am not sure if that will work due to how derive macros imports types.

Anyway, I this can be summarized in that I would like to reuse and contribute to glsl-layout as much as possible without forking it to adapt to notan. It would be great if you have any hint that can guide/lead me to this.

Thanks!

**Comment by zakarumych** [comment]
First part of question. To use glam types directly in the uniform structure and derive `Uniform` for it you'd need to implement `Std140` trait for the glam types. Ensure that layout is correct indeed.

Derive macro for `Uniform` outputs type reference that starts with `glsl_layout` symbol, so it won't compile if `glsl-layout` is not found.
I didn't prefixed it with `::` so it can look into local symbols. That means that if user imports `notan::glsl_layout` in the module where they derive `Uniform` it should work.

I can think of some alternatives.

**Comment by Nazariglez** [comment]
Found a workaround using your advice, no need to impl std140 but Uniform, works quite well. If this works for you I can send new PRs doing the same in the other math libs. Check #14 

I have also sent a PR to use const generics and allow any array size #12.

Let me know what you think. Thanks for the help!

**Comment by Nazariglez** [comment]
hey @zakarumych I added some PRs to support cgmath and nalgebra types as uniforms. Thanks

**Comment by Nazariglez** [comment]
Closing, thanks for the help!
